// <auto-generated />
using AddressBook.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBook.data.Migrations
{
    [DbContext(typeof(AddressBookContext))]
    [Migration("20241020201454_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AddressBook.data.Models.AddressBookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LocationLat")
                        .HasColumnType("REAL");

                    b.Property<double>("LocationLon")
                        .HasColumnType("REAL");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AddressBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ploiesti",
                            FirstName = "Adrian",
                            ImageName = "1.jpg",
                            LastName = "Cretu",
                            LocationLat = 44.940087766853466,
                            LocationLon = 26.024721381603694,
                            PhoneNumber = "0770390979"
                        },
                        new
                        {
                            Id = 2,
                            Address = "București",
                            FirstName = "Maria",
                            ImageName = "2.jpg",
                            LastName = "Ionescu",
                            LocationLat = 44.426767400000003,
                            LocationLon = 26.1025384,
                            PhoneNumber = "0741234567"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cluj-Napoca",
                            FirstName = "Ion",
                            ImageName = "3.jpg",
                            LastName = "Popescu",
                            LocationLat = 46.771210099999998,
                            LocationLon = 23.6236353,
                            PhoneNumber = "0732233444"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Iași",
                            FirstName = "Elena",
                            ImageName = "4.jpg",
                            LastName = "Vasilescu",
                            LocationLat = 47.156944000000003,
                            LocationLon = 27.590278000000001,
                            PhoneNumber = "0722233444"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Timișoara",
                            FirstName = "Mihai",
                            ImageName = "5.jpg",
                            LastName = "Georgescu",
                            LocationLat = 45.748871600000001,
                            LocationLon = 21.2086793,
                            PhoneNumber = "0711234567"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Brașov",
                            FirstName = "Ana",
                            ImageName = "6.jpg",
                            LastName = "Radu",
                            LocationLat = 45.657974600000003,
                            LocationLon = 25.601198199999999,
                            PhoneNumber = "0765234567"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Constanța",
                            FirstName = "Cristian",
                            ImageName = "7.jpg",
                            LastName = "Marin",
                            LocationLat = 44.159799999999997,
                            LocationLon = 28.634799999999998,
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Craiova",
                            FirstName = "Diana",
                            ImageName = "8.jpg",
                            LastName = "Tudor",
                            LocationLat = 44.330199999999998,
                            LocationLon = 23.794899999999998,
                            PhoneNumber = "0751234567"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Galați",
                            FirstName = "Victor",
                            ImageName = "9.jpg",
                            LastName = "Grigore",
                            LocationLat = 45.435299999999998,
                            LocationLon = 28.0077,
                            PhoneNumber = "0781234567"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Oradea",
                            FirstName = "Monica",
                            ImageName = "10.jpg",
                            LastName = "Dumitrescu",
                            LocationLat = 47.046500000000002,
                            LocationLon = 21.918900000000001,
                            PhoneNumber = "0791234567"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
